# -*- coding: utf-8 -*-

# Converted from PyQt5 to PyQt6
# PyQt6 key changes:
#   - QtCore.Qt enums are now namespaced: Qt.AlignCenter -> Qt.AlignmentFlag.AlignCenter
#   - QtWidgets.QFrame shape/shadow enums are namespaced
#   - No more exec_() → use exec()
#   - QAction moved to QtGui
#   - setGeometry with QRect works same way

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # ── Top bar: label ──
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 161, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setMouseTracking(True)
        self.label.setAutoFillBackground(True)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)

        # ── Top bar: search input ──
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(210, 20, 271, 41))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit.setTabletTracking(True)
        self.lineEdit.setAutoFillBackground(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_8.addWidget(self.lineEdit)

        # ── Top bar: Search button ──
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(500, 20, 121, 41))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton.setAutoFillBackground(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_9.addWidget(self.pushButton)

        # ── Top bar: Scrape button ──
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(650, 20, 121, 41))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_2.setAutoFillBackground(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_10.addWidget(self.pushButton_2)

        # ── Sidebar nav frame ──
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 90, 161, 441))
        # PyQt6: QFrame.Shape.StyledPanel, QFrame.Shadow.Raised
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")

        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 161, 31))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pushButton_3.setMouseTracking(True)
        self.pushButton_3.setAutoFillBackground(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_11.addWidget(self.pushButton_3)

        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(0, 30, 160, 31))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_4.setAutoFillBackground(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_12.addWidget(self.pushButton_4)

        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(0, 60, 160, 31))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.pushButton_5.setAutoFillBackground(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_13.addWidget(self.pushButton_5)

        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(0, 90, 160, 31))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.pushButton_6 = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.pushButton_6.setAutoFillBackground(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_14.addWidget(self.pushButton_6)

        # ── Stacked Widget ──
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(190, 90, 571, 441))
        self.stackedWidget.setObjectName("stackedWidget")

        # ── Page 3: Dashboard ──
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setAutoFillBackground(True)
        self.page_3.setObjectName("page_3")

        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.page_3)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(210, 20, 151, 41))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(10)
        self.label_2.setFont(font)
        # PyQt6: Qt.LayoutDirection.LeftToRight
        self.label_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_2.setAutoFillBackground(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_15.addWidget(self.label_2)

        # Stat card: Total Films
        self.frame_2 = QtWidgets.QFrame(self.page_3)
        self.frame_2.setGeometry(QtCore.QRect(50, 70, 120, 121))
        self.frame_2.setAutoFillBackground(True)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")

        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(10, 0, 101, 41))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        self.label_3.setAutoFillBackground(True)
        self.label_3.setScaledContents(True)
        # PyQt6: Qt.AlignmentFlag.AlignCenter
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_16.addWidget(self.label_3)

        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(10, 50, 101, 61))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        self.label_4.setAutoFillBackground(True)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_17.addWidget(self.label_4)

        # Stat card: Avg Rating
        self.frame_3 = QtWidgets.QFrame(self.page_3)
        self.frame_3.setGeometry(QtCore.QRect(220, 70, 120, 121))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")

        self.verticalLayoutWidget_14 = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(10, 0, 101, 41))
        self.verticalLayoutWidget_14.setObjectName("verticalLayoutWidget_14")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_14)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.label_7.setAutoFillBackground(True)
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_20.addWidget(self.label_7)

        self.verticalLayoutWidget_15 = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget_15.setGeometry(QtCore.QRect(10, 50, 101, 61))
        self.verticalLayoutWidget_15.setObjectName("verticalLayoutWidget_15")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_15)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.label_8.setAutoFillBackground(True)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_21.addWidget(self.label_8)

        # Stat card: Top Genre
        self.frame_4 = QtWidgets.QFrame(self.page_3)
        self.frame_4.setGeometry(QtCore.QRect(410, 70, 120, 121))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")

        self.verticalLayoutWidget_16 = QtWidgets.QWidget(self.frame_4)
        self.verticalLayoutWidget_16.setGeometry(QtCore.QRect(10, 0, 101, 41))
        self.verticalLayoutWidget_16.setObjectName("verticalLayoutWidget_16")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_16)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.label_9.setAutoFillBackground(True)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_22.addWidget(self.label_9)

        self.verticalLayoutWidget_17 = QtWidgets.QWidget(self.frame_4)
        self.verticalLayoutWidget_17.setGeometry(QtCore.QRect(10, 50, 101, 61))
        self.verticalLayoutWidget_17.setObjectName("verticalLayoutWidget_17")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_17)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_17)
        self.label_10.setAutoFillBackground(True)
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_23.addWidget(self.label_10)

        # Chart frame
        self.frame_5 = QtWidgets.QFrame(self.page_3)
        self.frame_5.setGeometry(QtCore.QRect(50, 210, 481, 231))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")

        self.label_11 = QtWidgets.QLabel(self.frame_5)
        self.label_11.setGeometry(QtCore.QRect(80, 20, 311, 20))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setAutoFillBackground(True)
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setObjectName("label_11")

        self.verticalLayoutWidget_18 = QtWidgets.QWidget(self.frame_5)
        self.verticalLayoutWidget_18.setGeometry(QtCore.QRect(0, 40, 481, 191))
        self.verticalLayoutWidget_18.setObjectName("verticalLayoutWidget_18")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_18)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.chart = QtWidgets.QWidget(self.verticalLayoutWidget_18)
        self.chart.setMouseTracking(True)
        self.chart.setTabletTracking(True)
        self.chart.setObjectName("chart")
        self.verticalLayout_24.addWidget(self.chart)

        self.stackedWidget.addWidget(self.page_3)

        # ── Page 4: Top 10 Movies ──
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setAutoFillBackground(True)
        self.page_4.setObjectName("page_4")

        self.verticalLayoutWidget_19 = QtWidgets.QWidget(self.page_4)
        self.verticalLayoutWidget_19.setGeometry(QtCore.QRect(20, 20, 351, 41))
        self.verticalLayoutWidget_19.setObjectName("verticalLayoutWidget_19")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_19)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_19)
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setAutoFillBackground(True)
        # PyQt6: combine alignment flags with |
        self.label_12.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading |
            QtCore.Qt.AlignmentFlag.AlignLeft |
            QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.label_12.setObjectName("label_12")
        self.verticalLayout_25.addWidget(self.label_12)

        self.tableWidget = QtWidgets.QTableWidget(self.page_4)
        self.tableWidget.setGeometry(QtCore.QRect(20, 70, 541, 361))
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)

        self.stackedWidget.addWidget(self.page_4)

        # ── Page 5: Genre Analysis ──
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setAutoFillBackground(True)
        self.page_5.setObjectName("page_5")

        self.verticalLayoutWidget_20 = QtWidgets.QWidget(self.page_5)
        self.verticalLayoutWidget_20.setGeometry(QtCore.QRect(10, 10, 341, 41))
        self.verticalLayoutWidget_20.setObjectName("verticalLayoutWidget_20")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_20)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_20)
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setAutoFillBackground(True)
        self.label_13.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading |
            QtCore.Qt.AlignmentFlag.AlignLeft |
            QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.label_13.setObjectName("label_13")
        self.verticalLayout_26.addWidget(self.label_13)

        self.verticalLayoutWidget_21 = QtWidgets.QWidget(self.page_5)
        self.verticalLayoutWidget_21.setGeometry(QtCore.QRect(10, 70, 251, 351))
        self.verticalLayoutWidget_21.setObjectName("verticalLayoutWidget_21")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_21)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.widget = QtWidgets.QWidget(self.verticalLayoutWidget_21)
        self.widget.setAutoFillBackground(True)
        self.widget.setObjectName("widget")
        self.verticalLayout_27.addWidget(self.widget)

        self.verticalLayoutWidget_22 = QtWidgets.QWidget(self.page_5)
        self.verticalLayoutWidget_22.setGeometry(QtCore.QRect(290, 70, 261, 41))
        self.verticalLayoutWidget_22.setObjectName("verticalLayoutWidget_22")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_22)
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_22)
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setAutoFillBackground(True)
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_28.addWidget(self.label_14)

        self.verticalLayoutWidget_23 = QtWidgets.QWidget(self.page_5)
        self.verticalLayoutWidget_23.setGeometry(QtCore.QRect(290, 120, 261, 301))
        self.verticalLayoutWidget_23.setObjectName("verticalLayoutWidget_23")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_23)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.widget_2 = QtWidgets.QWidget(self.verticalLayoutWidget_23)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_30.addWidget(self.widget_2)

        self.stackedWidget.addWidget(self.page_5)

        # ── Page 6: Movie Database Table ──
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")

        self.verticalLayoutWidget_25 = QtWidgets.QWidget(self.page_6)
        self.verticalLayoutWidget_25.setGeometry(QtCore.QRect(10, 20, 241, 21))
        self.verticalLayoutWidget_25.setObjectName("verticalLayoutWidget_25")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_25)
        self.verticalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_25)
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_32.addWidget(self.label_15)

        self.verticalLayoutWidget_26 = QtWidgets.QWidget(self.page_6)
        self.verticalLayoutWidget_26.setGeometry(QtCore.QRect(10, 60, 551, 371))
        self.verticalLayoutWidget_26.setObjectName("verticalLayoutWidget_26")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_26)
        self.verticalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.verticalLayoutWidget_26)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.verticalLayout_33.addWidget(self.tableWidget_2)

        self.stackedWidget.addWidget(self.page_6)

        # ── Page 7: Movie Details ──
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")

        self.verticalLayoutWidget_27 = QtWidgets.QWidget(self.page_7)
        self.verticalLayoutWidget_27.setGeometry(QtCore.QRect(20, 20, 261, 31))
        self.verticalLayoutWidget_27.setObjectName("verticalLayoutWidget_27")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_27)
        self.verticalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_27)
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setAutoFillBackground(True)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_34.addWidget(self.label_16)

        # Poster widget
        self.verticalLayoutWidget_28 = QtWidgets.QWidget(self.page_7)
        self.verticalLayoutWidget_28.setGeometry(QtCore.QRect(20, 60, 131, 181))
        self.verticalLayoutWidget_28.setObjectName("verticalLayoutWidget_28")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_28)
        self.verticalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.widget_6 = QtWidgets.QWidget(self.verticalLayoutWidget_28)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_35.addWidget(self.widget_6)

        # Info frame
        self.frame_6 = QtWidgets.QFrame(self.page_7)
        self.frame_6.setGeometry(QtCore.QRect(180, 60, 371, 181))
        self.frame_6.setAutoFillBackground(True)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")

        for (attr, geo, text_attr) in [
            ("verticalLayoutWidget_29", QtCore.QRect(0, 0, 160, 31), "label_17"),
            ("verticalLayoutWidget_30", QtCore.QRect(0, 30, 160, 21), "label_18"),
            ("verticalLayoutWidget_31", QtCore.QRect(0, 50, 160, 21), "label_19"),
            ("verticalLayoutWidget_32", QtCore.QRect(0, 70, 160, 21), "label_20"),
            ("verticalLayoutWidget_33", QtCore.QRect(0, 90, 160, 31), "label_21"),
            ("verticalLayoutWidget_34", QtCore.QRect(0, 120, 161, 31), "label_22"),
        ]:
            vw = QtWidgets.QWidget(self.frame_6)
            vw.setGeometry(geo)
            vw.setObjectName(attr)
            vl = QtWidgets.QVBoxLayout(vw)
            vl.setContentsMargins(0, 0, 0, 0)
            lbl = QtWidgets.QLabel(vw)
            lbl.setAutoFillBackground(True)
            lbl.setObjectName(text_attr)
            vl.addWidget(lbl)
            setattr(self, attr, vw)
            setattr(self, text_attr, lbl)

        # Available On section
        self.verticalLayoutWidget_35 = QtWidgets.QWidget(self.page_7)
        self.verticalLayoutWidget_35.setGeometry(QtCore.QRect(20, 270, 160, 41))
        self.verticalLayoutWidget_35.setObjectName("verticalLayoutWidget_35")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_35)
        self.verticalLayout_42.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget_35)
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setAutoFillBackground(True)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_42.addWidget(self.label_23)

        # Streaming platform labels
        self.widget_3 = QtWidgets.QWidget(self.page_7)
        self.widget_3.setGeometry(QtCore.QRect(19, 330, 151, 61))
        self.widget_3.setObjectName("widget_3")
        self.label_24 = QtWidgets.QLabel(self.widget_3)
        self.label_24.setGeometry(QtCore.QRect(40, 40, 55, 16))
        self.label_24.setAutoFillBackground(True)
        self.label_24.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_24.setObjectName("label_24")

        self.widget_4 = QtWidgets.QWidget(self.page_7)
        self.widget_4.setGeometry(QtCore.QRect(190, 330, 161, 61))
        self.widget_4.setObjectName("widget_4")
        self.label_25 = QtWidgets.QLabel(self.widget_4)
        self.label_25.setGeometry(QtCore.QRect(20, 40, 111, 20))
        self.label_25.setAutoFillBackground(True)
        self.label_25.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_25.setObjectName("label_25")

        self.widget_5 = QtWidgets.QWidget(self.page_7)
        self.widget_5.setGeometry(QtCore.QRect(370, 330, 151, 61))
        self.widget_5.setObjectName("widget_5")
        self.label_26 = QtWidgets.QLabel(self.widget_5)
        self.label_26.setGeometry(QtCore.QRect(50, 40, 55, 16))
        self.label_26.setAutoFillBackground(True)
        self.label_26.setObjectName("label_26")

        self.pushButton_8 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_8.setGeometry(QtCore.QRect(380, 400, 141, 28))
        self.pushButton_8.setObjectName("pushButton_8")

        self.stackedWidget.addWidget(self.page_7)

        # ── Central widget, menubar, statusbar ──
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setTabletTracking(True)
        self.menubar.setAutoFillBackground(True)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Movie Insight"))
        self.lineEdit.setText(_translate("MainWindow", "Search Film ..."))
        self.pushButton.setText(_translate("MainWindow", "Search"))
        self.pushButton_2.setText(_translate("MainWindow", "scrape"))
        self.pushButton_3.setText(_translate("MainWindow", "Dashboard"))
        self.pushButton_4.setText(_translate("MainWindow", "Top 10 Movies"))
        self.pushButton_5.setText(_translate("MainWindow", "Genre Analysis"))
        self.pushButton_6.setText(_translate("MainWindow", "MovieTable"))
        self.label_2.setText(_translate("MainWindow", "Movie Dashboard"))
        self.label_3.setText(_translate("MainWindow", "Total Films"))
        self.label_4.setText(_translate("MainWindow", "120 "))
        self.label_7.setText(_translate("MainWindow", "Avg Rating"))
        self.label_8.setText(_translate("MainWindow", "8.5"))
        self.label_9.setText(_translate("MainWindow", "Top Genre"))
        self.label_10.setText(_translate("MainWindow", "Action"))
        self.label_11.setText(_translate("MainWindow", "Rating Distribution Chart "))
        self.label_12.setText(_translate("MainWindow", "Top 10 Movies"))
        self.label_13.setText(_translate("MainWindow", "Genre Analysis"))
        self.label_14.setText(_translate("MainWindow", "Genre Summary"))
        self.label_15.setText(_translate("MainWindow", "Movie Database"))
        self.label_16.setText(_translate("MainWindow", "Movie Details"))
        self.label_17.setText(_translate("MainWindow", "Title    : Interstellar"))
        self.label_18.setText(_translate("MainWindow", "Year    : 2014"))
        self.label_19.setText(_translate("MainWindow", "Rating  : 8.6"))
        self.label_20.setText(_translate("MainWindow", "Votes   : 1.9 M"))
        self.label_21.setText(_translate("MainWindow", "Genre   : sci-Fi, Drama"))
        self.label_22.setText(_translate("MainWindow", "Duration:169 min"))
        self.label_23.setText(_translate("MainWindow", "Available On:"))
        self.label_24.setText(_translate("MainWindow", "Netflix"))
        self.label_25.setText(_translate("MainWindow", "Prime VIdeo"))
        self.label_26.setText(_translate("MainWindow", "Apple TV"))
        self.pushButton_8.setText(_translate("MainWindow", "Close"))
